// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbxePJrpQe6_QHylZ75cy4fv429yc8VjE',
    appId: '1:404343667183:web:716197fd2a4c155ddbde1a',
    messagingSenderId: '404343667183',
    projectId: 'dokan-stock',
    authDomain: 'dokan-stock.firebaseapp.com',
    storageBucket: 'dokan-stock.appspot.com',
    measurementId: 'G-Z4MDBKEK0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCha8Suy1pqdr8-MBenNrUDc00u08mQBn0',
    appId: '1:404343667183:android:30df4d43ecb5bd5cdbde1a',
    messagingSenderId: '404343667183',
    projectId: 'dokan-stock',
    storageBucket: 'dokan-stock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvce7coxEqu7GKcnr69FRzrIlytCGiYCU',
    appId: '1:404343667183:ios:45f9f796ba4b2342dbde1a',
    messagingSenderId: '404343667183',
    projectId: 'dokan-stock',
    storageBucket: 'dokan-stock.appspot.com',
    iosBundleId: 'com.example.dokanStock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvce7coxEqu7GKcnr69FRzrIlytCGiYCU',
    appId: '1:404343667183:ios:e11436be53438d05dbde1a',
    messagingSenderId: '404343667183',
    projectId: 'dokan-stock',
    storageBucket: 'dokan-stock.appspot.com',
    iosBundleId: 'com.example.dokanStock.RunnerTests',
  );
}
